#!/bin/bash

# create the path to volume
path=$(pwd)

# get root password from env var
pswd=$(echo "$MYSQL_ROOT_PASSWORD")

# check to see if there is a container running
out=$(docker ps -la)
tocheck="mysql"

#if there is a container with the mysql name, then remove it
if [[ "$out" == *"$tocheck"* ]]; then
	docker rm mysql
fi

#run the docker container to hold mysql
docker run --name=mysql -e MYSQL_ROOT_PASSWORD="root" -v ${path}/vol:/var/lib/mysql -p 3306:3306 -d mysql:latest
